[2024-06-27T08:57:13.750+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T08:57:13.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-27T08:57:13.785+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-27T08:57:13.786+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 5
[2024-06-27T08:57:13.802+0000] {taskinstance.py:2330} INFO - Executing <Task(ExtractData): extract_data> on 2024-06-23 00:00:00+00:00
[2024-06-27T08:57:13.814+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T08:57:13.816+0000] {standard_task_runner.py:63} INFO - Started process 206 to run task
[2024-06-27T08:57:13.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'peduli_pintar_etl_dags_v3', 'extract_data', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmp78s7xepp']
[2024-06-27T08:57:13.820+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask extract_data
[2024-06-27T08:57:13.907+0000] {task_command.py:426} INFO - Running <TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-23T00:00:00+00:00 [running]> on host 3dad981482d5
[2024-06-27T08:57:14.030+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='peduli_pintar_etl_dags_v3' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-27T08:57:14.033+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T08:57:14.074+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:14.528+0000] {sql.py:487} INFO - Running statement: SHOW TABLES, parameters: None
[2024-06-27T08:57:14.557+0000] {sql.py:496} INFO - Rows affected: 23
[2024-06-27T08:57:14.625+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:17.968+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admin_notifications, parameters: None
[2024-06-27T08:57:18.008+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T08:57:18.226+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:18.563+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM admin_notifications
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:18.599+0000] {sql.py:496} INFO - Rows affected: 14
[2024-06-27T08:57:19.134+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:19.491+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admins, parameters: None
[2024-06-27T08:57:19.525+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T08:57:19.601+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:19.913+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM admins
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:19.946+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T08:57:20.121+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:21.399+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM applications, parameters: None
[2024-06-27T08:57:21.434+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-27T08:57:21.619+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:21.874+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM applications
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:21.908+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T08:57:22.003+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:22.264+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM articles, parameters: None
[2024-06-27T08:57:22.298+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T08:57:22.398+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:24.894+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM articles
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:25.002+0000] {sql.py:496} INFO - Rows affected: 3
[2024-06-27T08:57:25.288+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:25.603+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM chatbots, parameters: None
[2024-06-27T08:57:25.636+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T08:57:25.788+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:27.850+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM chatbots
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:27.884+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T08:57:28.008+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:28.347+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM comments, parameters: None
[2024-06-27T08:57:28.382+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T08:57:28.450+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:28.764+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM comments
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:28.803+0000] {sql.py:496} INFO - Rows affected: 31
[2024-06-27T08:57:28.890+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:29.272+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_comments, parameters: None
[2024-06-27T08:57:29.318+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T08:57:30.105+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:30.453+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_comments
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:30.504+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T08:57:30.702+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:30.997+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manual_comments, parameters: None
[2024-06-27T08:57:31.037+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T08:57:31.437+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:31.986+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_manual_comments
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:32.053+0000] {sql.py:496} INFO - Rows affected: 5
[2024-06-27T08:57:32.572+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:32.955+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manuals, parameters: None
[2024-06-27T08:57:32.998+0000] {sql.py:496} INFO - Rows affected: 9
[2024-06-27T08:57:33.106+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:33.465+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_manuals
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:33.498+0000] {sql.py:496} INFO - Rows affected: 15
[2024-06-27T08:57:33.657+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:33.967+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donations, parameters: None
[2024-06-27T08:57:34.002+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-27T08:57:34.167+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:35.552+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donations
            WHERE DATE(created_at) = '2024-06-23' OR DATE(updated_at) = '2024-06-23'
        , parameters: None
[2024-06-27T08:57:35.729+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T08:57:35.968+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:36.389+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraising_categories, parameters: None
[2024-06-27T08:57:36.524+0000] {sql.py:496} INFO - Rows affected: 5
[2024-06-27T08:57:37.152+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T08:57:49.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T08:57:49.775+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 56, in execute
    dataframes, table_names = self.extract_data_from_external_db(formatted_query, text_columns)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 34, in extract_data_from_external_db
    data = mysql_hook.get_records(formatted_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 303, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1159, 'Got timeout reading communication packets')
[2024-06-27T08:57:50.856+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=peduli_pintar_etl_dags_v3, task_id=extract_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240627T085713, end_date=20240627T085750
[2024-06-27T08:57:51.101+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task extract_data ((1159, 'Got timeout reading communication packets'); 206)
[2024-06-27T08:57:51.253+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T08:57:51.837+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T08:57:51.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
