[2024-06-27T09:02:45.773+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T09:02:45.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T09:02:45.839+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-27T09:02:45.840+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 5
[2024-06-27T09:02:45.871+0000] {taskinstance.py:2330} INFO - Executing <Task(ExtractData): extract_data> on 2024-06-25 00:00:00+00:00
[2024-06-27T09:02:45.901+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T09:02:45.915+0000] {standard_task_runner.py:63} INFO - Started process 354 to run task
[2024-06-27T09:02:45.905+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'peduli_pintar_etl_dags_v3', 'extract_data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmptbyao52r']
[2024-06-27T09:02:45.932+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask extract_data
[2024-06-27T09:02:46.275+0000] {task_command.py:426} INFO - Running <TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-25T00:00:00+00:00 [running]> on host 3dad981482d5
[2024-06-27T09:02:46.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='peduli_pintar_etl_dags_v3' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-27T09:02:46.511+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T09:02:46.573+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:47.919+0000] {sql.py:487} INFO - Running statement: SHOW TABLES, parameters: None
[2024-06-27T09:02:47.950+0000] {sql.py:496} INFO - Rows affected: 23
[2024-06-27T09:02:47.989+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:48.302+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admin_notifications, parameters: None
[2024-06-27T09:02:48.334+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:48.382+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:48.678+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM admin_notifications
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:48.707+0000] {sql.py:496} INFO - Rows affected: 3
[2024-06-27T09:02:48.760+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:49.056+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admins, parameters: None
[2024-06-27T09:02:49.086+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:49.127+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:49.422+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM admins
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:49.451+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:49.500+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:49.811+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM applications, parameters: None
[2024-06-27T09:02:49.843+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-27T09:02:49.883+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:50.266+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM applications
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:50.297+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:50.336+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:51.663+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM articles, parameters: None
[2024-06-27T09:02:51.695+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:51.744+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:52.043+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM articles
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:52.074+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-27T09:02:52.134+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:53.910+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM chatbots, parameters: None
[2024-06-27T09:02:53.941+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T09:02:53.995+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:54.336+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM chatbots
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:54.365+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:54.409+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:56.672+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM comments, parameters: None
[2024-06-27T09:02:56.704+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:56.752+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:58.199+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM comments
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:58.233+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:58.534+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:58.943+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_comments, parameters: None
[2024-06-27T09:02:58.973+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T09:02:59.013+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:59.323+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_comments
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:02:59.352+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:59.408+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:59.713+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manual_comments, parameters: None
[2024-06-27T09:02:59.744+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T09:02:59.800+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:00.105+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_manual_comments
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:00.141+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-27T09:03:00.192+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:00.497+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manuals, parameters: None
[2024-06-27T09:03:00.529+0000] {sql.py:496} INFO - Rows affected: 9
[2024-06-27T09:03:00.568+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:00.915+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_manuals
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:00.944+0000] {sql.py:496} INFO - Rows affected: 2
[2024-06-27T09:03:00.982+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:02.277+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donations, parameters: None
[2024-06-27T09:03:02.309+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-27T09:03:02.347+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:02.620+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donations
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:02.652+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:02.707+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:03.035+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraising_categories, parameters: None
[2024-06-27T09:03:03.069+0000] {sql.py:496} INFO - Rows affected: 5
[2024-06-27T09:03:03.114+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:04.424+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM fundraising_categories
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:04.457+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:04.537+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:05.912+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraisings, parameters: None
[2024-06-27T09:03:05.988+0000] {sql.py:496} INFO - Rows affected: 14
[2024-06-27T09:03:06.077+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:06.485+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM fundraisings
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:06.519+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-27T09:03:06.585+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:06.969+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM like_donation_comments, parameters: None
[2024-06-27T09:03:07.003+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-27T09:03:07.052+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:07.366+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM like_donation_comments
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:07.404+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:07.471+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:07.787+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM like_donation_manual_comments, parameters: None
[2024-06-27T09:03:07.819+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-27T09:03:07.863+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:08.173+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM like_donation_manual_comments
            WHERE DATE(created_at) = '2024-06-25' OR DATE(updated_at) = '2024-06-25'
        , parameters: None
[2024-06-27T09:03:08.203+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:08.259+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:08.633+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM likes_comments, parameters: None
[2024-06-27T09:03:08.665+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-27T09:03:08.721+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:37.793+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T09:03:38.058+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 56, in execute
    dataframes, table_names = self.extract_data_from_external_db(formatted_query, text_columns)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 34, in extract_data_from_external_db
    data = mysql_hook.get_records(formatted_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 303, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1159, 'Got timeout reading communication packets')
[2024-06-27T09:03:43.721+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=peduli_pintar_etl_dags_v3, task_id=extract_data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240627T090245, end_date=20240627T090343
[2024-06-27T09:03:45.481+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task extract_data ((1159, 'Got timeout reading communication packets'); 354)
[2024-06-27T09:03:45.679+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T09:03:46.368+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T09:03:46.379+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
