[2024-06-26T11:27:08.210+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T11:27:08.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peduli_pintar_elt_all_dags.load_db_local scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-26T11:27:08.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peduli_pintar_elt_all_dags.load_db_local scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-26T11:27:08.245+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-06-26T11:27:08.260+0000] {taskinstance.py:2330} INFO - Executing <Task(LoadDatabaseLocal): load_db_local> on 2024-06-24 00:00:00+00:00
[2024-06-26T11:27:08.270+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=416) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T11:27:08.273+0000] {standard_task_runner.py:63} INFO - Started process 430 to run task
[2024-06-26T11:27:08.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'peduli_pintar_elt_all_dags', 'load_db_local', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/etl_all_dags.py', '--cfg-path', '/tmp/tmph0cdr93n']
[2024-06-26T11:27:08.274+0000] {standard_task_runner.py:91} INFO - Job 399: Subtask load_db_local
[2024-06-26T11:27:08.343+0000] {task_command.py:426} INFO - Running <TaskInstance: peduli_pintar_elt_all_dags.load_db_local scheduled__2024-06-24T00:00:00+00:00 [running]> on host 5338995eebdf
[2024-06-26T11:27:08.445+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='peduli_pintar_elt_all_dags' AIRFLOW_CTX_TASK_ID='load_db_local' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-06-26T11:27:08.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T11:27:08.470+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-06-26T11:27:08.517+0000] {etl_all_operator.py:384} INFO - Connected to MySQL database 'peduli_pintar' on server 'IkaPurwanti'
[2024-06-26T11:27:08.518+0000] {etl_all_operator.py:390} INFO - Connection to MySQL with connection ID 'mysql_default' is successful.
[2024-06-26T11:27:08.519+0000] {etl_all_operator.py:509} INFO - Connection DB sukses!!!
[2024-06-26T11:27:08.649+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-06-26T11:27:11.810+0000] {etl_all_operator.py:497} INFO - Data berhasil disimpan ke tabel-tabel dalam database 'peduli_pintar'.
[2024-06-26T11:27:11.811+0000] {etl_all_operator.py:519} INFO - Data insertion completed successfully.
[2024-06-26T11:27:11.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T11:27:11.829+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=peduli_pintar_elt_all_dags, task_id=load_db_local, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20240626T112708, end_date=20240626T112711
[2024-06-26T11:27:11.904+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T11:27:11.933+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T11:27:11.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
