[2024-06-23T13:02:55.394+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:02:55.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:02:55.415+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:02:55.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:03:24.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:03:24.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 29.366 seconds
[2024-06-23T13:04:01.116+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:04:01.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:04:01.224+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:04:01.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:04:20.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:04:20.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 21.545 seconds
[2024-06-23T13:04:51.385+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:04:51.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:04:51.392+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:04:51.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:04:52.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:04:52.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.390 seconds
[2024-06-23T13:05:24.252+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:05:24.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:05:24.530+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:05:24.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:05:27.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:05:27.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 4.134 seconds
[2024-06-23T13:05:58.524+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:05:58.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:05:58.543+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:05:58.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:06:03.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:06:04.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 5.653 seconds
[2024-06-23T13:06:37.152+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:06:37.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:06:37.159+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:06:37.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:06:39.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:06:39.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 2.352 seconds
[2024-06-23T13:07:09.999+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:07:10.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:07:10.006+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:07:10.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:07:11.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:07:11.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.149 seconds
[2024-06-23T13:07:41.955+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:07:41.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:07:41.959+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:07:41.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:07:43.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:07:43.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.181 seconds
[2024-06-23T13:08:14.193+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:08:14.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:08:14.199+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:08:14.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:08:15.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:08:15.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.958 seconds
[2024-06-23T13:08:45.889+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:08:45.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:08:45.894+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:08:45.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:08:46.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:08:46.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.937 seconds
[2024-06-23T13:09:17.102+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:09:17.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:09:17.112+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:09:17.111+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:09:19.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:09:20.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 3.018 seconds
[2024-06-23T13:09:51.018+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:09:51.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:09:51.091+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:09:51.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:10:29.634+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:10:29.629+0000] {timeout.py:68} ERROR - Process timed out, PID: 208
[2024-06-23T13:13:13.809+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:13:13.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:13:13.905+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:13:13.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:13:20.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:13:30.864+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-23T13:16:32.332+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:16:32.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:16:32.345+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:16:32.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:16:53.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:16:53.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 21.124 seconds
[2024-06-23T13:17:24.211+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:17:24.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:17:24.217+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:17:24.216+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:17:25.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:17:25.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.338 seconds
[2024-06-23T13:17:56.345+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:17:56.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:17:56.386+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:17:56.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:18:44.944+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:18:29.587+0000] {timeout.py:68} ERROR - Process timed out, PID: 68
[2024-06-23T13:32:43.608+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:32:44.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:32:44.241+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:32:44.221+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:33:09.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:33:09.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 26.854 seconds
[2024-06-23T13:33:47.604+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:33:47.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:33:47.622+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:33:47.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:33:54.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:33:54.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 6.989 seconds
[2024-06-23T13:34:25.886+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:34:26.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:34:26.199+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:34:26.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:34:31.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:34:31.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 5.945 seconds
[2024-06-23T13:38:11.116+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:38:11.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:38:11.203+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:38:11.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:38:16.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:38:16.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 5.465 seconds
[2024-06-23T13:41:04.845+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:41:04.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T13:41:04.855+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:41:04.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T13:42:27.753+0000] {logging_mixin.py:188} INFO - [2024-06-23T13:41:55.158+0000] {timeout.py:68} ERROR - Process timed out, PID: 139
[2024-06-23T14:03:48.347+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:03:48.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:03:48.362+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:03:48.360+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:04:09.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:04:09.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 21.243 seconds
[2024-06-23T14:06:53.671+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:06:53.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:06:53.786+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:06:53.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:07:41.019+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:07:33.206+0000] {timeout.py:68} ERROR - Process timed out, PID: 61
[2024-06-23T14:08:22.459+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:08:22.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:08:22.463+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:08:22.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:08:23.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:08:23.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.683 seconds
[2024-06-23T14:08:53.620+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:08:53.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:08:53.626+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:08:53.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:08:54.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:08:54.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.750 seconds
[2024-06-23T14:09:24.777+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:09:24.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:09:24.801+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:09:24.800+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:09:30.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:09:30.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 6.073 seconds
[2024-06-23T14:10:01.455+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:01.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:10:01.459+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:10:01.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:06.044+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:06.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 4.709 seconds
[2024-06-23T14:10:27.387+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:27.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:10:27.408+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:10:27.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:28.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:28.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.296 seconds
[2024-06-23T14:10:44.337+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:44.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:10:44.386+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:10:44.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:46.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:10:46.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.919 seconds
[2024-06-23T14:11:16.456+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:11:16.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:11:16.460+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:11:16.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:11:17.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:11:17.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.834 seconds
[2024-06-23T14:11:47.641+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:11:47.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:11:47.659+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:11:47.658+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:12:23.072+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:12:22.983+0000] {timeout.py:68} ERROR - Process timed out, PID: 131
[2024-06-23T14:13:36.155+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:13:36.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:13:36.159+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:13:36.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:13:37.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:13:37.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.617 seconds
[2024-06-23T14:14:08.240+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:14:08.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:14:08.242+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:14:08.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:14:08.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:14:08.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.688 seconds
[2024-06-23T14:14:39.406+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:14:39.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:14:39.408+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:14:39.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:14:40.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:14:40.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.243 seconds
[2024-06-23T14:15:10.919+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:15:10.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:15:10.924+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:15:10.924+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:15:12.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:15:12.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.335 seconds
[2024-06-23T14:16:23.527+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:16:23.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:16:23.586+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:16:23.568+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:16:45.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:16:45.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 22.362 seconds
[2024-06-23T14:17:15.851+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:17:15.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:17:15.861+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:17:15.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:17:22.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:17:32.548+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-23T14:18:03.597+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:18:03.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:18:03.605+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:18:03.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:18:04.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:18:04.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 1.029 seconds
[2024-06-23T14:18:37.993+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:18:38.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:18:38.686+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:18:38.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:19:28.977+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:19:15.747+0000] {timeout.py:68} ERROR - Process timed out, PID: 261
[2024-06-23T14:49:32.949+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:49:32.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:49:32.957+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:49:32.956+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:49:38.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:49:38.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 5.372 seconds
[2024-06-23T14:50:20.954+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:50:20.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:50:20.961+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:50:20.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:50:25.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:50:25.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 4.496 seconds
[2024-06-23T14:51:26.123+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:51:26.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:51:26.143+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:51:26.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:51:28.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:51:28.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 2.267 seconds
[2024-06-23T14:51:58.567+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:51:58.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:51:58.573+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:51:58.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:52:00.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:52:00.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 2.175 seconds
[2024-06-23T14:52:30.983+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:52:30.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:52:30.987+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:52:30.987+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:52:31.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:52:31.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.793 seconds
[2024-06-23T14:53:17.267+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:53:17.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:53:17.275+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:53:17.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:53:44.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:53:45.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 28.253 seconds
[2024-06-23T14:54:15.661+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:54:15.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:54:15.663+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:54:15.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:54:16.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:54:16.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/etl_all_operator.py took 0.759 seconds
[2024-06-23T14:54:46.897+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:54:46.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:54:46.905+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:54:46.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:55:17.039+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:55:16.953+0000] {timeout.py:68} ERROR - Process timed out, PID: 145
[2024-06-23T14:55:48.333+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T14:55:48.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T14:55:48.348+0000] {logging_mixin.py:188} INFO - [2024-06-23T14:55:48.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:01:13.887+0000] {logging_mixin.py:188} INFO - [2024-06-23T15:00:33.916+0000] {timeout.py:68} ERROR - Process timed out, PID: 169
[2024-06-23T15:01:53.492+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:01:53.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T15:01:53.542+0000] {logging_mixin.py:188} INFO - [2024-06-23T15:01:53.502+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:11:24.587+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:11:24.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T15:11:24.703+0000] {logging_mixin.py:188} INFO - [2024-06-23T15:11:24.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:21:23.888+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:21:23.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/etl_all_operator.py for tasks to queue
[2024-06-23T15:21:24.173+0000] {logging_mixin.py:188} INFO - [2024-06-23T15:21:24.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/etl_all_operator.py
[2024-06-23T15:23:08.623+0000] {logging_mixin.py:188} INFO - [2024-06-23T15:22:09.419+0000] {timeout.py:68} ERROR - Process timed out, PID: 47
