[2024-06-27T09:02:45.773+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T09:02:45.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-26T00:00:00+00:00 [queued]>
[2024-06-27T09:02:45.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-26T00:00:00+00:00 [queued]>
[2024-06-27T09:02:45.845+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 5
[2024-06-27T09:02:45.872+0000] {taskinstance.py:2330} INFO - Executing <Task(ExtractData): extract_data> on 2024-06-26 00:00:00+00:00
[2024-06-27T09:02:45.908+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=351) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T09:02:45.905+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'peduli_pintar_etl_dags_v3', 'extract_data', 'scheduled__2024-06-26T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpxez55sup']
[2024-06-27T09:02:45.921+0000] {standard_task_runner.py:63} INFO - Started process 355 to run task
[2024-06-27T09:02:45.923+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask extract_data
[2024-06-27T09:02:46.273+0000] {task_command.py:426} INFO - Running <TaskInstance: peduli_pintar_etl_dags_v3.extract_data scheduled__2024-06-26T00:00:00+00:00 [running]> on host 3dad981482d5
[2024-06-27T09:02:46.528+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='peduli_pintar_etl_dags_v3' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T00:00:00+00:00'
[2024-06-27T09:02:46.531+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T09:02:46.573+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:47.919+0000] {sql.py:487} INFO - Running statement: SHOW TABLES, parameters: None
[2024-06-27T09:02:47.953+0000] {sql.py:496} INFO - Rows affected: 23
[2024-06-27T09:02:47.989+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:48.301+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admin_notifications, parameters: None
[2024-06-27T09:02:48.335+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:48.373+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:48.680+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM admin_notifications
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:48.710+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:48.807+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:49.056+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM admins, parameters: None
[2024-06-27T09:02:49.087+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:49.139+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:49.422+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM admins
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:49.451+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:49.499+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:49.810+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM applications, parameters: None
[2024-06-27T09:02:49.843+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-27T09:02:49.883+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:50.253+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM applications
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:50.285+0000] {sql.py:496} INFO - Rows affected: 2
[2024-06-27T09:02:50.339+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:51.663+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM articles, parameters: None
[2024-06-27T09:02:51.695+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:51.738+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:52.043+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM articles
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:52.074+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:52.125+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:53.903+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM chatbots, parameters: None
[2024-06-27T09:02:53.939+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T09:02:53.995+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:54.335+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM chatbots
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:54.363+0000] {sql.py:496} INFO - Rows affected: 3
[2024-06-27T09:02:54.404+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:56.672+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM comments, parameters: None
[2024-06-27T09:02:56.703+0000] {sql.py:496} INFO - Rows affected: 8
[2024-06-27T09:02:56.752+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:58.197+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM comments
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:58.231+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:58.536+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:58.942+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_comments, parameters: None
[2024-06-27T09:02:58.973+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T09:02:59.013+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:59.324+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_comments
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:02:59.353+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:02:59.413+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:02:59.713+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manual_comments, parameters: None
[2024-06-27T09:02:59.744+0000] {sql.py:496} INFO - Rows affected: 7
[2024-06-27T09:02:59.787+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:00.106+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_manual_comments
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:00.141+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:00.185+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:00.488+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donation_manuals, parameters: None
[2024-06-27T09:03:00.517+0000] {sql.py:496} INFO - Rows affected: 9
[2024-06-27T09:03:00.563+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:00.916+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donation_manuals
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:00.945+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:00.982+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:02.268+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM donations, parameters: None
[2024-06-27T09:03:02.297+0000] {sql.py:496} INFO - Rows affected: 11
[2024-06-27T09:03:02.331+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:02.623+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM donations
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:02.653+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:02.704+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:03.035+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraising_categories, parameters: None
[2024-06-27T09:03:03.069+0000] {sql.py:496} INFO - Rows affected: 5
[2024-06-27T09:03:03.114+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:04.424+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM fundraising_categories
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:04.457+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:04.526+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:05.954+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM fundraisings, parameters: None
[2024-06-27T09:03:06.008+0000] {sql.py:496} INFO - Rows affected: 14
[2024-06-27T09:03:06.089+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:06.506+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM fundraisings
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:06.545+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:06.606+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:06.969+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM like_donation_comments, parameters: None
[2024-06-27T09:03:07.004+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-27T09:03:07.052+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:07.366+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM like_donation_comments
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:07.405+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:07.489+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:07.786+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM like_donation_manual_comments, parameters: None
[2024-06-27T09:03:07.819+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-27T09:03:07.863+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:08.171+0000] {sql.py:487} INFO - Running statement: 
            SELECT *
            FROM like_donation_manual_comments
            WHERE DATE(created_at) = '2024-06-26' OR DATE(updated_at) = '2024-06-26'
        , parameters: None
[2024-06-27T09:03:08.202+0000] {sql.py:496} INFO - Rows affected: 0
[2024-06-27T09:03:08.260+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:08.633+0000] {sql.py:487} INFO - Running statement: SHOW COLUMNS FROM likes_comments, parameters: None
[2024-06-27T09:03:08.666+0000] {sql.py:496} INFO - Rows affected: 6
[2024-06-27T09:03:08.721+0000] {base.py:84} INFO - Using connection ID 'EXTERNAL_DB_CONN_CAPSTONE_DE' for task execution.
[2024-06-27T09:03:37.795+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T09:03:38.091+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 56, in execute
    dataframes, table_names = self.extract_data_from_external_db(formatted_query, text_columns)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operator/etl_operator.py", line 34, in extract_data_from_external_db
    data = mysql_hook.get_records(formatted_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 303, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1159, 'Got timeout reading communication packets')
[2024-06-27T09:03:44.307+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=peduli_pintar_etl_dags_v3, task_id=extract_data, run_id=scheduled__2024-06-26T00:00:00+00:00, execution_date=20240626T000000, start_date=20240627T090245, end_date=20240627T090343
[2024-06-27T09:03:45.479+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task extract_data ((1159, 'Got timeout reading communication packets'); 355)
[2024-06-27T09:03:45.659+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T09:03:46.543+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T09:03:46.564+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
